spring.application.name=auth-service
server.port=8001

spring.config.import=file:./secrets/db.properties

## JPA ##
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

## DATABASE ##
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=didrik
spring.datasource.password=${db_password}
spring.datasource.driver-class-name=org.postgresql.Driver

## JWT ##
spring.security.jwt.secret=${jwt_secret}
spring.security.jwt.expiration=${jwt_expiration}
