services:
  auth-db:
    image: postgres:15
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U auth -d authdb" ]
      interval: 5s
      timeout: 5s
      retries: 10

  auth-service:
    build: .
    ports:
      - "8001:8001"
    env_file:
      - ./secrets/db.properties
    environment:
      SERVER_PORT: 8001
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/authdb
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_USERNAME: auth
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      auth-db:
        condition: service_healthy
    volumes:
      - ./auth-service/secrets:/app/secrets

volumes:
    auth-db-data:
